### ISSUE TITLE
Readme does not describe how to use this

### ISSUE THREAD

**Issue by sroberson** [romario333/grunt-debug-task#4]
There is something wrong with this.  I used to be able to debug grunt tasks in chrome and set breakpoints, etc.  I developed/tweaked several grunt tasks about 9 months ago. But now, despite a lot of Googling around for this, i have no idea how to debug grunt tasks anymore.  What gives? Did people stop using Grunt?  Should I start porting stuff to Gulp?

**Comment by romario333** [comment]
What version of Node.js are you on? It works for 0.10 but does not work for 0.12.

Anyways while investigating this I've found a better way how to debug grunt tasks with node-inspector (or any other Node.js code):

    npm install -g node-inspector
    node-debug grunt whatever

This works on io.js and node.js 0.10. node-inspector seems to have issues on node.js 0.12 though (`Runtime.getProperties failed. Object #-3# not found`).

I'm thinking about deprecating this plugin in favor of `node-debug`. Can you try whether it works for you?

**Comment by sroberson** [comment]
Ah.  Yes, I am on node v0.12.0.  I just installed 'nvm' and then installed node:

    nvm install 0.10
    node --version
    v0.10.38
    npm install node-inspector  # note not global 
    node-debug grunt inlinecss

This starts the debugger, but doesn't seem to be listing my local files.  Before it would show the local files, but my breakpoints were ignored.

**Comment by romario333** [comment]
Ok, so I've upgraded `node-inspector` used in `grunt-debug-task`, retested it on node `v0.10.38` and `v0.12.4` and both seem to work ok now. I've published fixed version.

I would still recommend going with `node-debug` though.
